package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo  implements java.io.Serializable {


     private Integer idArticulo;
     private Departamento departamento;
     private Factura factura;
     private Proveedores proveedores;
     private String nombre;
     private String concepto;
     private Double precio;
     private byte[] foto;
     private String categoria;
     private String codigo;
     private Boolean suministrado;
     private Set ofertas = new HashSet(0);

    public Articulo() {
    }

	
    public Articulo(Departamento departamento, Factura factura) {
        this.departamento = departamento;
        this.factura = factura;
    }
    public Articulo(Departamento departamento, Factura factura, Proveedores proveedores, String nombre, String concepto, Double precio, byte[] foto, String categoria, String codigo, Boolean suministrado, Set ofertas) {
       this.departamento = departamento;
       this.factura = factura;
       this.proveedores = proveedores;
       this.nombre = nombre;
       this.concepto = concepto;
       this.precio = precio;
       this.foto = foto;
       this.categoria = categoria;
       this.codigo = codigo;
       this.suministrado = suministrado;
       this.ofertas = ofertas;
    }
   
    public Integer getIdArticulo() {
        return this.idArticulo;
    }
    
    public void setIdArticulo(Integer idArticulo) {
        this.idArticulo = idArticulo;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Factura getFactura() {
        return this.factura;
    }
    
    public void setFactura(Factura factura) {
        this.factura = factura;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Boolean getSuministrado() {
        return this.suministrado;
    }
    
    public void setSuministrado(Boolean suministrado) {
        this.suministrado = suministrado;
    }
    public Set getOfertas() {
        return this.ofertas;
    }
    
    public void setOfertas(Set ofertas) {
        this.ofertas = ofertas;
    }




}


