package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Contrato generated by hbm2java
 */
public class Contrato  implements java.io.Serializable {


     private Integer idContrato;
     private Empleado empleado;
     private String condiciones;
     private String categoria;
     private Double salario;
     private String concepto;
     private String horario;
     private String tipo;
     private Set parteTieneContratos = new HashSet(0);

    public Contrato() {
    }

	
    public Contrato(Empleado empleado, String condiciones) {
        this.empleado = empleado;
        this.condiciones = condiciones;
    }
    public Contrato(Empleado empleado, String condiciones, String categoria, Double salario, String concepto, String horario, String tipo, Set parteTieneContratos) {
       this.empleado = empleado;
       this.condiciones = condiciones;
       this.categoria = categoria;
       this.salario = salario;
       this.concepto = concepto;
       this.horario = horario;
       this.tipo = tipo;
       this.parteTieneContratos = parteTieneContratos;
    }
   
    public Integer getIdContrato() {
        return this.idContrato;
    }
    
    public void setIdContrato(Integer idContrato) {
        this.idContrato = idContrato;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getCondiciones() {
        return this.condiciones;
    }
    
    public void setCondiciones(String condiciones) {
        this.condiciones = condiciones;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Double getSalario() {
        return this.salario;
    }
    
    public void setSalario(Double salario) {
        this.salario = salario;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getParteTieneContratos() {
        return this.parteTieneContratos;
    }
    
    public void setParteTieneContratos(Set parteTieneContratos) {
        this.parteTieneContratos = parteTieneContratos;
    }




}


