package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamento generated by hbm2java
 */
public class Departamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private Empleado empleado;
     private String nombre;
     private Set empleados = new HashSet(0);
     private Set parteTieneDepartamentos = new HashSet(0);
     private Set articulos = new HashSet(0);

    public Departamento() {
    }

    public Departamento(Empleado empleado, String nombre, Set empleados, Set parteTieneDepartamentos, Set articulos) {
       this.empleado = empleado;
       this.nombre = nombre;
       this.empleados = empleados;
       this.parteTieneDepartamentos = parteTieneDepartamentos;
       this.articulos = articulos;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }
    public Set getParteTieneDepartamentos() {
        return this.parteTieneDepartamentos;
    }
    
    public void setParteTieneDepartamentos(Set parteTieneDepartamentos) {
        this.parteTieneDepartamentos = parteTieneDepartamentos;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }




}


