package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Diatrabajo generated by hbm2java
 */
public class Diatrabajo  implements java.io.Serializable {


     private Integer diaTrabajo;
     private Empleado empleado;
     private Date fecha;
     private Date horasTrabajadas;
     private Date horaExtra;
     private String concepto;
     private String categoria;
     private String sector;

    public Diatrabajo() {
    }

	
    public Diatrabajo(Empleado empleado, Date fecha, Date horasTrabajadas) {
        this.empleado = empleado;
        this.fecha = fecha;
        this.horasTrabajadas = horasTrabajadas;
    }
    public Diatrabajo(Empleado empleado, Date fecha, Date horasTrabajadas, Date horaExtra, String concepto, String categoria, String sector) {
       this.empleado = empleado;
       this.fecha = fecha;
       this.horasTrabajadas = horasTrabajadas;
       this.horaExtra = horaExtra;
       this.concepto = concepto;
       this.categoria = categoria;
       this.sector = sector;
    }
   
    public Integer getDiaTrabajo() {
        return this.diaTrabajo;
    }
    
    public void setDiaTrabajo(Integer diaTrabajo) {
        this.diaTrabajo = diaTrabajo;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Date getHorasTrabajadas() {
        return this.horasTrabajadas;
    }
    
    public void setHorasTrabajadas(Date horasTrabajadas) {
        this.horasTrabajadas = horasTrabajadas;
    }
    public Date getHoraExtra() {
        return this.horaExtra;
    }
    
    public void setHoraExtra(Date horaExtra) {
        this.horaExtra = horaExtra;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }




}


