package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private Integer idEmpleado;
     private Departamento departamento;
     private String idiomas;
     private String habilidades;
     private String sector;
     private String categoria;
     private String rol;
     private byte[] foto;
     private String numeroSeguridadSocial;
     private String codigoPostal;
     private String calle;
     private Integer numero;
     private String pais;
     private String ciudad;
     private String poblacion;
     private String via;
     private String escalera;
     private String bloque;
     private String provincia;
     private String nombre;
     private String primerApellido;
     private String segundoApellido;
     private Date fechaNacimiento;
     private String dni;
     private String sexo;
     private String correoElectronico;
     private String telefonoMovil;
     private String telefonoFijo;
     private Boolean discapacitado;
     private String usuario;
     private String password;
     private Set partesForEmpleadoIdEmpleadoCierra = new HashSet(0);
     private Set departamentos = new HashSet(0);
     private Set reservas = new HashSet(0);
     private Set diatrabajos = new HashSet(0);
     private Set contratos = new HashSet(0);
     private Set partesForEmpleadoIdEmpleadoAbre = new HashSet(0);
     private Set parteTieneEmpleados = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(String rol, String dni, String usuario, String password) {
        this.rol = rol;
        this.dni = dni;
        this.usuario = usuario;
        this.password = password;
    }
    public Empleado(Departamento departamento, String idiomas, String habilidades, String sector, String categoria, String rol, byte[] foto, String numeroSeguridadSocial, String codigoPostal, String calle, Integer numero, String pais, String ciudad, String poblacion, String via, String escalera, String bloque, String provincia, String nombre, String primerApellido, String segundoApellido, Date fechaNacimiento, String dni, String sexo, String correoElectronico, String telefonoMovil, String telefonoFijo, Boolean discapacitado, String usuario, String password, Set partesForEmpleadoIdEmpleadoCierra, Set departamentos, Set reservas, Set diatrabajos, Set contratos, Set partesForEmpleadoIdEmpleadoAbre, Set parteTieneEmpleados) {
       this.departamento = departamento;
       this.idiomas = idiomas;
       this.habilidades = habilidades;
       this.sector = sector;
       this.categoria = categoria;
       this.rol = rol;
       this.foto = foto;
       this.numeroSeguridadSocial = numeroSeguridadSocial;
       this.codigoPostal = codigoPostal;
       this.calle = calle;
       this.numero = numero;
       this.pais = pais;
       this.ciudad = ciudad;
       this.poblacion = poblacion;
       this.via = via;
       this.escalera = escalera;
       this.bloque = bloque;
       this.provincia = provincia;
       this.nombre = nombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.fechaNacimiento = fechaNacimiento;
       this.dni = dni;
       this.sexo = sexo;
       this.correoElectronico = correoElectronico;
       this.telefonoMovil = telefonoMovil;
       this.telefonoFijo = telefonoFijo;
       this.discapacitado = discapacitado;
       this.usuario = usuario;
       this.password = password;
       this.partesForEmpleadoIdEmpleadoCierra = partesForEmpleadoIdEmpleadoCierra;
       this.departamentos = departamentos;
       this.reservas = reservas;
       this.diatrabajos = diatrabajos;
       this.contratos = contratos;
       this.partesForEmpleadoIdEmpleadoAbre = partesForEmpleadoIdEmpleadoAbre;
       this.parteTieneEmpleados = parteTieneEmpleados;
    }
   
    public Integer getIdEmpleado() {
        return this.idEmpleado;
    }
    
    public void setIdEmpleado(Integer idEmpleado) {
        this.idEmpleado = idEmpleado;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public String getIdiomas() {
        return this.idiomas;
    }
    
    public void setIdiomas(String idiomas) {
        this.idiomas = idiomas;
    }
    public String getHabilidades() {
        return this.habilidades;
    }
    
    public void setHabilidades(String habilidades) {
        this.habilidades = habilidades;
    }
    public String getSector() {
        return this.sector;
    }
    
    public void setSector(String sector) {
        this.sector = sector;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }
    public String getNumeroSeguridadSocial() {
        return this.numeroSeguridadSocial;
    }
    
    public void setNumeroSeguridadSocial(String numeroSeguridadSocial) {
        this.numeroSeguridadSocial = numeroSeguridadSocial;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getVia() {
        return this.via;
    }
    
    public void setVia(String via) {
        this.via = via;
    }
    public String getEscalera() {
        return this.escalera;
    }
    
    public void setEscalera(String escalera) {
        this.escalera = escalera;
    }
    public String getBloque() {
        return this.bloque;
    }
    
    public void setBloque(String bloque) {
        this.bloque = bloque;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }
    
    public void setTelefonoMovil(String telefonoMovil) {
        this.telefonoMovil = telefonoMovil;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    public Boolean getDiscapacitado() {
        return this.discapacitado;
    }
    
    public void setDiscapacitado(Boolean discapacitado) {
        this.discapacitado = discapacitado;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getPartesForEmpleadoIdEmpleadoCierra() {
        return this.partesForEmpleadoIdEmpleadoCierra;
    }
    
    public void setPartesForEmpleadoIdEmpleadoCierra(Set partesForEmpleadoIdEmpleadoCierra) {
        this.partesForEmpleadoIdEmpleadoCierra = partesForEmpleadoIdEmpleadoCierra;
    }
    public Set getDepartamentos() {
        return this.departamentos;
    }
    
    public void setDepartamentos(Set departamentos) {
        this.departamentos = departamentos;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getDiatrabajos() {
        return this.diatrabajos;
    }
    
    public void setDiatrabajos(Set diatrabajos) {
        this.diatrabajos = diatrabajos;
    }
    public Set getContratos() {
        return this.contratos;
    }
    
    public void setContratos(Set contratos) {
        this.contratos = contratos;
    }
    public Set getPartesForEmpleadoIdEmpleadoAbre() {
        return this.partesForEmpleadoIdEmpleadoAbre;
    }
    
    public void setPartesForEmpleadoIdEmpleadoAbre(Set partesForEmpleadoIdEmpleadoAbre) {
        this.partesForEmpleadoIdEmpleadoAbre = partesForEmpleadoIdEmpleadoAbre;
    }
    public Set getParteTieneEmpleados() {
        return this.parteTieneEmpleados;
    }
    
    public void setParteTieneEmpleados(Set parteTieneEmpleados) {
        this.parteTieneEmpleados = parteTieneEmpleados;
    }




}


