package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresa generated by hbm2java
 */
public class Empresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private String nombre;
     private String razonSocial;
     private String nif;
     private String actividad;
     private String tipo;
     private String paginaWeb;
     private String correoElectronico;
     private String codigoPostal;
     private String calle;
     private Integer numero;
     private String pais;
     private String ciudad;
     private String poblacion;
     private String via;
     private String escalera;
     private String bloque;
     private String provincia;
     private Set proveedoreses = new HashSet(0);
     private Set facturas = new HashSet(0);
     private Set ofertaTieneEmpresas = new HashSet(0);
     private Set parteTieneEmpresas = new HashSet(0);
     private Set agencias = new HashSet(0);

    public Empresa() {
    }

    public Empresa(String nombre, String razonSocial, String nif, String actividad, String tipo, String paginaWeb, String correoElectronico, String codigoPostal, String calle, Integer numero, String pais, String ciudad, String poblacion, String via, String escalera, String bloque, String provincia, Set proveedoreses, Set facturas, Set ofertaTieneEmpresas, Set parteTieneEmpresas, Set agencias) {
       this.nombre = nombre;
       this.razonSocial = razonSocial;
       this.nif = nif;
       this.actividad = actividad;
       this.tipo = tipo;
       this.paginaWeb = paginaWeb;
       this.correoElectronico = correoElectronico;
       this.codigoPostal = codigoPostal;
       this.calle = calle;
       this.numero = numero;
       this.pais = pais;
       this.ciudad = ciudad;
       this.poblacion = poblacion;
       this.via = via;
       this.escalera = escalera;
       this.bloque = bloque;
       this.provincia = provincia;
       this.proveedoreses = proveedoreses;
       this.facturas = facturas;
       this.ofertaTieneEmpresas = ofertaTieneEmpresas;
       this.parteTieneEmpresas = parteTieneEmpresas;
       this.agencias = agencias;
    }
   
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getNif() {
        return this.nif;
    }
    
    public void setNif(String nif) {
        this.nif = nif;
    }
    public String getActividad() {
        return this.actividad;
    }
    
    public void setActividad(String actividad) {
        this.actividad = actividad;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getPaginaWeb() {
        return this.paginaWeb;
    }
    
    public void setPaginaWeb(String paginaWeb) {
        this.paginaWeb = paginaWeb;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getCodigoPostal() {
        return this.codigoPostal;
    }
    
    public void setCodigoPostal(String codigoPostal) {
        this.codigoPostal = codigoPostal;
    }
    public String getCalle() {
        return this.calle;
    }
    
    public void setCalle(String calle) {
        this.calle = calle;
    }
    public Integer getNumero() {
        return this.numero;
    }
    
    public void setNumero(Integer numero) {
        this.numero = numero;
    }
    public String getPais() {
        return this.pais;
    }
    
    public void setPais(String pais) {
        this.pais = pais;
    }
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }
    public String getPoblacion() {
        return this.poblacion;
    }
    
    public void setPoblacion(String poblacion) {
        this.poblacion = poblacion;
    }
    public String getVia() {
        return this.via;
    }
    
    public void setVia(String via) {
        this.via = via;
    }
    public String getEscalera() {
        return this.escalera;
    }
    
    public void setEscalera(String escalera) {
        this.escalera = escalera;
    }
    public String getBloque() {
        return this.bloque;
    }
    
    public void setBloque(String bloque) {
        this.bloque = bloque;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public Set getProveedoreses() {
        return this.proveedoreses;
    }
    
    public void setProveedoreses(Set proveedoreses) {
        this.proveedoreses = proveedoreses;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getOfertaTieneEmpresas() {
        return this.ofertaTieneEmpresas;
    }
    
    public void setOfertaTieneEmpresas(Set ofertaTieneEmpresas) {
        this.ofertaTieneEmpresas = ofertaTieneEmpresas;
    }
    public Set getParteTieneEmpresas() {
        return this.parteTieneEmpresas;
    }
    
    public void setParteTieneEmpresas(Set parteTieneEmpresas) {
        this.parteTieneEmpresas = parteTieneEmpresas;
    }
    public Set getAgencias() {
        return this.agencias;
    }
    
    public void setAgencias(Set agencias) {
        this.agencias = agencias;
    }




}


