package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private Integer idFactura;
     private Cliente cliente;
     private Empresa empresa;
     private Oferta oferta;
     private Date fechaLiquidacion;
     private String empleadoPersonaDni;
     private String concepto;
     private String codigo;
     private Boolean propia;
     private Set articulos = new HashSet(0);

    public Factura() {
    }

    public Factura(Cliente cliente, Empresa empresa, Oferta oferta, Date fechaLiquidacion, String empleadoPersonaDni, String concepto, String codigo, Boolean propia, Set articulos) {
       this.cliente = cliente;
       this.empresa = empresa;
       this.oferta = oferta;
       this.fechaLiquidacion = fechaLiquidacion;
       this.empleadoPersonaDni = empleadoPersonaDni;
       this.concepto = concepto;
       this.codigo = codigo;
       this.propia = propia;
       this.articulos = articulos;
    }
   
    public Integer getIdFactura() {
        return this.idFactura;
    }
    
    public void setIdFactura(Integer idFactura) {
        this.idFactura = idFactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }
    public Date getFechaLiquidacion() {
        return this.fechaLiquidacion;
    }
    
    public void setFechaLiquidacion(Date fechaLiquidacion) {
        this.fechaLiquidacion = fechaLiquidacion;
    }
    public String getEmpleadoPersonaDni() {
        return this.empleadoPersonaDni;
    }
    
    public void setEmpleadoPersonaDni(String empleadoPersonaDni) {
        this.empleadoPersonaDni = empleadoPersonaDni;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Boolean getPropia() {
        return this.propia;
    }
    
    public void setPropia(Boolean propia) {
        this.propia = propia;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }




}


