package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * HabitacionTieneCliente generated by hbm2java
 */
public class HabitacionTieneCliente  implements java.io.Serializable {


     private HabitacionTieneClienteId id;
     private Cliente cliente;
     private Habitacion habitacion;
     private Date fechaInicio;
     private Date fechaFin;

    public HabitacionTieneCliente() {
    }

	
    public HabitacionTieneCliente(HabitacionTieneClienteId id, Cliente cliente, Habitacion habitacion) {
        this.id = id;
        this.cliente = cliente;
        this.habitacion = habitacion;
    }
    public HabitacionTieneCliente(HabitacionTieneClienteId id, Cliente cliente, Habitacion habitacion, Date fechaInicio, Date fechaFin) {
       this.id = id;
       this.cliente = cliente;
       this.habitacion = habitacion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public HabitacionTieneClienteId getId() {
        return this.id;
    }
    
    public void setId(HabitacionTieneClienteId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Habitacion getHabitacion() {
        return this.habitacion;
    }
    
    public void setHabitacion(Habitacion habitacion) {
        this.habitacion = habitacion;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


