package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1



/**
 * HabitacionTieneClienteId generated by hbm2java
 */
public class HabitacionTieneClienteId  implements java.io.Serializable {


     private int habitacionIdHabitacion;
     private int clienteIdCliente;

    public HabitacionTieneClienteId() {
    }

    public HabitacionTieneClienteId(int habitacionIdHabitacion, int clienteIdCliente) {
       this.habitacionIdHabitacion = habitacionIdHabitacion;
       this.clienteIdCliente = clienteIdCliente;
    }
   
    public int getHabitacionIdHabitacion() {
        return this.habitacionIdHabitacion;
    }
    
    public void setHabitacionIdHabitacion(int habitacionIdHabitacion) {
        this.habitacionIdHabitacion = habitacionIdHabitacion;
    }
    public int getClienteIdCliente() {
        return this.clienteIdCliente;
    }
    
    public void setClienteIdCliente(int clienteIdCliente) {
        this.clienteIdCliente = clienteIdCliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof HabitacionTieneClienteId) ) return false;
		 HabitacionTieneClienteId castOther = ( HabitacionTieneClienteId ) other; 
         
		 return (this.getHabitacionIdHabitacion()==castOther.getHabitacionIdHabitacion())
 && (this.getClienteIdCliente()==castOther.getClienteIdCliente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getHabitacionIdHabitacion();
         result = 37 * result + this.getClienteIdCliente();
         return result;
   }   


}


