package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1



/**
 * MesaTieneClienteId generated by hbm2java
 */
public class MesaTieneClienteId  implements java.io.Serializable {


     private int mesaIdMesa;
     private int clienteIdCliente;

    public MesaTieneClienteId() {
    }

    public MesaTieneClienteId(int mesaIdMesa, int clienteIdCliente) {
       this.mesaIdMesa = mesaIdMesa;
       this.clienteIdCliente = clienteIdCliente;
    }
   
    public int getMesaIdMesa() {
        return this.mesaIdMesa;
    }
    
    public void setMesaIdMesa(int mesaIdMesa) {
        this.mesaIdMesa = mesaIdMesa;
    }
    public int getClienteIdCliente() {
        return this.clienteIdCliente;
    }
    
    public void setClienteIdCliente(int clienteIdCliente) {
        this.clienteIdCliente = clienteIdCliente;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MesaTieneClienteId) ) return false;
		 MesaTieneClienteId castOther = ( MesaTieneClienteId ) other; 
         
		 return (this.getMesaIdMesa()==castOther.getMesaIdMesa())
 && (this.getClienteIdCliente()==castOther.getClienteIdCliente());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getMesaIdMesa();
         result = 37 * result + this.getClienteIdCliente();
         return result;
   }   


}


