package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * MesaTieneCliente generated by hbm2java
 */
public class MesaTieneCliente  implements java.io.Serializable {


     private MesaTieneClienteId id;
     private Cliente cliente;
     private Mesa mesa;
     private Date fechaInicio;
     private Date fechaFin;
     private Boolean desayuno;
     private Boolean almuerzo;
     private Boolean cena;

    public MesaTieneCliente() {
    }

	
    public MesaTieneCliente(MesaTieneClienteId id, Cliente cliente, Mesa mesa) {
        this.id = id;
        this.cliente = cliente;
        this.mesa = mesa;
    }
    public MesaTieneCliente(MesaTieneClienteId id, Cliente cliente, Mesa mesa, Date fechaInicio, Date fechaFin, Boolean desayuno, Boolean almuerzo, Boolean cena) {
       this.id = id;
       this.cliente = cliente;
       this.mesa = mesa;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.desayuno = desayuno;
       this.almuerzo = almuerzo;
       this.cena = cena;
    }
   
    public MesaTieneClienteId getId() {
        return this.id;
    }
    
    public void setId(MesaTieneClienteId id) {
        this.id = id;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Mesa getMesa() {
        return this.mesa;
    }
    
    public void setMesa(Mesa mesa) {
        this.mesa = mesa;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Boolean getDesayuno() {
        return this.desayuno;
    }
    
    public void setDesayuno(Boolean desayuno) {
        this.desayuno = desayuno;
    }
    public Boolean getAlmuerzo() {
        return this.almuerzo;
    }
    
    public void setAlmuerzo(Boolean almuerzo) {
        this.almuerzo = almuerzo;
    }
    public Boolean getCena() {
        return this.cena;
    }
    
    public void setCena(Boolean cena) {
        this.cena = cena;
    }




}


