package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Oferta generated by hbm2java
 */
public class Oferta  implements java.io.Serializable {


     private Integer idOferta;
     private Articulo articulo;
     private Double precio;
     private Double descuento;
     private Date fechaInicio;
     private String clientePersonaDni;
     private String empleadoPersonaDni;
     private Date fechaFin;
     private String concepto;
     private String categoria;
     private Set parteTieneOfertas = new HashSet(0);
     private Set facturas = new HashSet(0);
     private Set reservas = new HashSet(0);
     private Set ofertaTieneEmpresas = new HashSet(0);

    public Oferta() {
    }

    public Oferta(Articulo articulo, Double precio, Double descuento, Date fechaInicio, String clientePersonaDni, String empleadoPersonaDni, Date fechaFin, String concepto, String categoria, Set parteTieneOfertas, Set facturas, Set reservas, Set ofertaTieneEmpresas) {
       this.articulo = articulo;
       this.precio = precio;
       this.descuento = descuento;
       this.fechaInicio = fechaInicio;
       this.clientePersonaDni = clientePersonaDni;
       this.empleadoPersonaDni = empleadoPersonaDni;
       this.fechaFin = fechaFin;
       this.concepto = concepto;
       this.categoria = categoria;
       this.parteTieneOfertas = parteTieneOfertas;
       this.facturas = facturas;
       this.reservas = reservas;
       this.ofertaTieneEmpresas = ofertaTieneEmpresas;
    }
   
    public Integer getIdOferta() {
        return this.idOferta;
    }
    
    public void setIdOferta(Integer idOferta) {
        this.idOferta = idOferta;
    }
    public Articulo getArticulo() {
        return this.articulo;
    }
    
    public void setArticulo(Articulo articulo) {
        this.articulo = articulo;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Double getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(Double descuento) {
        this.descuento = descuento;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public String getClientePersonaDni() {
        return this.clientePersonaDni;
    }
    
    public void setClientePersonaDni(String clientePersonaDni) {
        this.clientePersonaDni = clientePersonaDni;
    }
    public String getEmpleadoPersonaDni() {
        return this.empleadoPersonaDni;
    }
    
    public void setEmpleadoPersonaDni(String empleadoPersonaDni) {
        this.empleadoPersonaDni = empleadoPersonaDni;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Set getParteTieneOfertas() {
        return this.parteTieneOfertas;
    }
    
    public void setParteTieneOfertas(Set parteTieneOfertas) {
        this.parteTieneOfertas = parteTieneOfertas;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getReservas() {
        return this.reservas;
    }
    
    public void setReservas(Set reservas) {
        this.reservas = reservas;
    }
    public Set getOfertaTieneEmpresas() {
        return this.ofertaTieneEmpresas;
    }
    
    public void setOfertaTieneEmpresas(Set ofertaTieneEmpresas) {
        this.ofertaTieneEmpresas = ofertaTieneEmpresas;
    }




}


