package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * OfertaTieneEmpresa generated by hbm2java
 */
public class OfertaTieneEmpresa  implements java.io.Serializable {


     private Integer idOfertaTieneEmpresa;
     private Empresa empresa;
     private Oferta oferta;
     private Date fechaInicio;
     private Date fechaFin;

    public OfertaTieneEmpresa() {
    }

	
    public OfertaTieneEmpresa(Empresa empresa, Oferta oferta) {
        this.empresa = empresa;
        this.oferta = oferta;
    }
    public OfertaTieneEmpresa(Empresa empresa, Oferta oferta, Date fechaInicio, Date fechaFin) {
       this.empresa = empresa;
       this.oferta = oferta;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getIdOfertaTieneEmpresa() {
        return this.idOfertaTieneEmpresa;
    }
    
    public void setIdOfertaTieneEmpresa(Integer idOfertaTieneEmpresa) {
        this.idOfertaTieneEmpresa = idOfertaTieneEmpresa;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


