package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ParteTieneEmpresa generated by hbm2java
 */
public class ParteTieneEmpresa  implements java.io.Serializable {


     private Integer idparteTieneEmpresa;
     private Empresa empresa;
     private Parte parte;
     private Date fechaInicio;
     private Date fechaFin;

    public ParteTieneEmpresa() {
    }

	
    public ParteTieneEmpresa(Empresa empresa, Parte parte) {
        this.empresa = empresa;
        this.parte = parte;
    }
    public ParteTieneEmpresa(Empresa empresa, Parte parte, Date fechaInicio, Date fechaFin) {
       this.empresa = empresa;
       this.parte = parte;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getIdparteTieneEmpresa() {
        return this.idparteTieneEmpresa;
    }
    
    public void setIdparteTieneEmpresa(Integer idparteTieneEmpresa) {
        this.idparteTieneEmpresa = idparteTieneEmpresa;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Parte getParte() {
        return this.parte;
    }
    
    public void setParte(Parte parte) {
        this.parte = parte;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


