package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ParteTieneDepartamento generated by hbm2java
 */
public class ParteTieneDepartamento  implements java.io.Serializable {


     private Integer idparteTieneDepartamentocol;
     private Departamento departamento;
     private Parte parte;
     private Date fechaInicio;
     private Date fechaFin;

    public ParteTieneDepartamento() {
    }

	
    public ParteTieneDepartamento(Departamento departamento, Parte parte) {
        this.departamento = departamento;
        this.parte = parte;
    }
    public ParteTieneDepartamento(Departamento departamento, Parte parte, Date fechaInicio, Date fechaFin) {
       this.departamento = departamento;
       this.parte = parte;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getIdparteTieneDepartamentocol() {
        return this.idparteTieneDepartamentocol;
    }
    
    public void setIdparteTieneDepartamentocol(Integer idparteTieneDepartamentocol) {
        this.idparteTieneDepartamentocol = idparteTieneDepartamentocol;
    }
    public Departamento getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(Departamento departamento) {
        this.departamento = departamento;
    }
    public Parte getParte() {
        return this.parte;
    }
    
    public void setParte(Parte parte) {
        this.parte = parte;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


