package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ParteTieneProveedores generated by hbm2java
 */
public class ParteTieneProveedores  implements java.io.Serializable {


     private Integer idparteTieneProveedores;
     private Parte parte;
     private Proveedores proveedores;
     private Date fechaInicio;
     private Date fechaFin;

    public ParteTieneProveedores() {
    }

	
    public ParteTieneProveedores(Parte parte, Proveedores proveedores) {
        this.parte = parte;
        this.proveedores = proveedores;
    }
    public ParteTieneProveedores(Parte parte, Proveedores proveedores, Date fechaInicio, Date fechaFin) {
       this.parte = parte;
       this.proveedores = proveedores;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getIdparteTieneProveedores() {
        return this.idparteTieneProveedores;
    }
    
    public void setIdparteTieneProveedores(Integer idparteTieneProveedores) {
        this.idparteTieneProveedores = idparteTieneProveedores;
    }
    public Parte getParte() {
        return this.parte;
    }
    
    public void setParte(Parte parte) {
        this.parte = parte;
    }
    public Proveedores getProveedores() {
        return this.proveedores;
    }
    
    public void setProveedores(Proveedores proveedores) {
        this.proveedores = proveedores;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


