package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ParteTieneReserva generated by hbm2java
 */
public class ParteTieneReserva  implements java.io.Serializable {


     private int idparteTieneReserva;
     private Parte parte;
     private Reserva reserva;
     private Date fechaInicio;
     private Date fechaFin;

    public ParteTieneReserva() {
    }

	
    public ParteTieneReserva(int idparteTieneReserva, Parte parte, Reserva reserva) {
        this.idparteTieneReserva = idparteTieneReserva;
        this.parte = parte;
        this.reserva = reserva;
    }
    public ParteTieneReserva(int idparteTieneReserva, Parte parte, Reserva reserva, Date fechaInicio, Date fechaFin) {
       this.idparteTieneReserva = idparteTieneReserva;
       this.parte = parte;
       this.reserva = reserva;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public int getIdparteTieneReserva() {
        return this.idparteTieneReserva;
    }
    
    public void setIdparteTieneReserva(int idparteTieneReserva) {
        this.idparteTieneReserva = idparteTieneReserva;
    }
    public Parte getParte() {
        return this.parte;
    }
    
    public void setParte(Parte parte) {
        this.parte = parte;
    }
    public Reserva getReserva() {
        return this.reserva;
    }
    
    public void setReserva(Reserva reserva) {
        this.reserva = reserva;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


