package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ParteTieneOferta generated by hbm2java
 */
public class ParteTieneOferta  implements java.io.Serializable {


     private Integer idparteTieneOferta;
     private Oferta oferta;
     private Parte parte;
     private Date fechaInicio;
     private Date fechaFin;

    public ParteTieneOferta() {
    }

	
    public ParteTieneOferta(Oferta oferta, Parte parte) {
        this.oferta = oferta;
        this.parte = parte;
    }
    public ParteTieneOferta(Oferta oferta, Parte parte, Date fechaInicio, Date fechaFin) {
       this.oferta = oferta;
       this.parte = parte;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
    }
   
    public Integer getIdparteTieneOferta() {
        return this.idparteTieneOferta;
    }
    
    public void setIdparteTieneOferta(Integer idparteTieneOferta) {
        this.idparteTieneOferta = idparteTieneOferta;
    }
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }
    public Parte getParte() {
        return this.parte;
    }
    
    public void setParte(Parte parte) {
        this.parte = parte;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }




}


