package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Proveedores generated by hbm2java
 */
public class Proveedores  implements java.io.Serializable {


     private Integer idProveedores;
     private Empresa empresa;
     private String cateoria;
     private String clasificacion;
     private String nombre;
     private String primerApellido;
     private String segundoApellido;
     private Date fechaNacimiento;
     private String dni;
     private String sexo;
     private String correoElectronico;
     private String telefonoMovil;
     private String telefonoFijo;
     private Boolean discapacitado;
     private Set parteTieneProveedoreses = new HashSet(0);
     private Set articulos = new HashSet(0);

    public Proveedores() {
    }

	
    public Proveedores(String dni) {
        this.dni = dni;
    }
    public Proveedores(Empresa empresa, String cateoria, String clasificacion, String nombre, String primerApellido, String segundoApellido, Date fechaNacimiento, String dni, String sexo, String correoElectronico, String telefonoMovil, String telefonoFijo, Boolean discapacitado, Set parteTieneProveedoreses, Set articulos) {
       this.empresa = empresa;
       this.cateoria = cateoria;
       this.clasificacion = clasificacion;
       this.nombre = nombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.fechaNacimiento = fechaNacimiento;
       this.dni = dni;
       this.sexo = sexo;
       this.correoElectronico = correoElectronico;
       this.telefonoMovil = telefonoMovil;
       this.telefonoFijo = telefonoFijo;
       this.discapacitado = discapacitado;
       this.parteTieneProveedoreses = parteTieneProveedoreses;
       this.articulos = articulos;
    }
   
    public Integer getIdProveedores() {
        return this.idProveedores;
    }
    
    public void setIdProveedores(Integer idProveedores) {
        this.idProveedores = idProveedores;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public String getCateoria() {
        return this.cateoria;
    }
    
    public void setCateoria(String cateoria) {
        this.cateoria = cateoria;
    }
    public String getClasificacion() {
        return this.clasificacion;
    }
    
    public void setClasificacion(String clasificacion) {
        this.clasificacion = clasificacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }
    
    public void setTelefonoMovil(String telefonoMovil) {
        this.telefonoMovil = telefonoMovil;
    }
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }
    public Boolean getDiscapacitado() {
        return this.discapacitado;
    }
    
    public void setDiscapacitado(Boolean discapacitado) {
        this.discapacitado = discapacitado;
    }
    public Set getParteTieneProveedoreses() {
        return this.parteTieneProveedoreses;
    }
    
    public void setParteTieneProveedoreses(Set parteTieneProveedoreses) {
        this.parteTieneProveedoreses = parteTieneProveedoreses;
    }
    public Set getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Set articulos) {
        this.articulos = articulos;
    }




}


