package dam.gestionhotelera.modelo.Pojos;
// Generated 02-dic-2017 19:12:02 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reserva generated by hbm2java
 */
public class Reserva  implements java.io.Serializable {


     private Integer idReserva;
     private Agencia agencia;
     private Empleado empleado;
     private Oferta oferta;
     private Date fechaInicio;
     private String pension;
     private Date fechaFin;
     private Set clientes = new HashSet(0);
     private Set parteTieneReservas = new HashSet(0);

    public Reserva() {
    }

	
    public Reserva(Agencia agencia, Empleado empleado, Date fechaInicio, Date fechaFin) {
        this.agencia = agencia;
        this.empleado = empleado;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
    }
    public Reserva(Agencia agencia, Empleado empleado, Oferta oferta, Date fechaInicio, String pension, Date fechaFin, Set clientes, Set parteTieneReservas) {
       this.agencia = agencia;
       this.empleado = empleado;
       this.oferta = oferta;
       this.fechaInicio = fechaInicio;
       this.pension = pension;
       this.fechaFin = fechaFin;
       this.clientes = clientes;
       this.parteTieneReservas = parteTieneReservas;
    }
   
    public Integer getIdReserva() {
        return this.idReserva;
    }
    
    public void setIdReserva(Integer idReserva) {
        this.idReserva = idReserva;
    }
    public Agencia getAgencia() {
        return this.agencia;
    }
    
    public void setAgencia(Agencia agencia) {
        this.agencia = agencia;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Oferta getOferta() {
        return this.oferta;
    }
    
    public void setOferta(Oferta oferta) {
        this.oferta = oferta;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public String getPension() {
        return this.pension;
    }
    
    public void setPension(String pension) {
        this.pension = pension;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }
    public Set getParteTieneReservas() {
        return this.parteTieneReservas;
    }
    
    public void setParteTieneReservas(Set parteTieneReservas) {
        this.parteTieneReservas = parteTieneReservas;
    }




}


